[package]
name = "crustls"
version = "0.7.1"
authors = ["Jacob Hoffman-Andrews <github@hoffman-andrews.com>"]
description = "C-to-rustls bindings"
edition = "2018"
links = "crustls"

[dependencies]
# Keep in sync with RUSTLS_CRATE_VERSION in lib.rs
rustls = { version = "=0.20", features = [ "dangerous_configuration" ] }
webpki = "0.22"
libc = "0.2"
sct = "0.7"
rustls-pemfile = "0.2.1"
log = "0.4.14"

[dev_dependencies]
cbindgen = "*"

[lib]
name = "crustls"
crate-type = ["lib", "staticlib"]
